### ISSUE TITLE
what kind of binary cc2530-prog could burn ?

### ISSUE THREAD

**Issue by pengphei** [ffainelli/cc2530prog#4]
Hello, ffainelli.

I am trying to burn cc2530 firmware with cc2530-prog. but I have no idea what kind of firmware should be used for burning? I only have hex binary built with iar workbench.

Regards!

**Comment by ffainelli** [comment]
cc2530prog was used to flash the bootloader binary image to the CC2530 target. It does not support any kind of other binary format. AFAIR, the bootloader project in IAR workbench should have proper output targets that take care of that already.
